"use strict";

/**
 * js/config/BalanceConfig.js
 * ⚖️ BALANCE — Runtime gameplay constants, shop items, and achievements.
 */

const BALANCE = {
  physics: {
    friction: 0.88,
    acceleration: 1800,
  },
  player: {
    obstacleWarningRange: 35,
    obstacleBuffPower: 1.25,
    obstacleBuffDuration: 1.0,
    obstacleWarningCooldown: 3000,
    secondWindHpPct: 0.2,
    secondWindSpeedMult: 1.3,
    secondWindDamageMult: 1.5,
    // ⚠️  DEPRECATED — source of truth is BALANCE.characters.auto
    auto: {
      hp: 150,
      speed: 160,
      energyRegen: 20,
      heatWaveRange: 180,
      wanchaiDuration: 4.0,
      wanchaiCooldown: 12,
    },
  },
  characters: {
    kao: {
      name: "Kao",
      radius: 20,
      hp: 119,
      maxHp: 119,
      energy: 100,
      maxEnergy: 100,
      energyRegen: 15,
      moveSpeed: 298,
      dashSpeed: 550,
      dashDistance: 180,
      weapons: {
        auto: {
          name: "AUTO RIFLE",
          damage: 26,
          cooldown: 0.22,
          range: 900,
          speed: 900,
          spread: 0,
          pellets: 1,
          color: "#3b82f6",
          icon: "🔵",
        },
        sniper: {
          name: "SNIPER",
          damage: 95,
          cooldown: 0.85,
          range: 1200,
          speed: 1200,
          spread: 0,
          pellets: 1,
          color: "#ef4444",
          icon: "🔴",
        },
        shotgun: {
          name: "SHOTGUN",
          damage: 28,
          cooldown: 0.55,
          range: 400,
          speed: 700,
          spread: 0.45,
          pellets: 3,
          color: "#f59e0b",
          icon: "🟠",
        },
      },
      baseCritChance: 0.05,
      critMultiplier: 2.5,
      dashCooldown: 1.65,
      stealthCooldown: 5.5,
      stealthCost: 25,
      stealthDrain: 45,
      stealthSpeedBonus: 1.5,
      expToNextLevel: 100,
      expLevelMult: 1.3,
      passiveUnlockLevel: 1,
      passiveUnlockStealthCount: 1,
      passiveHpBonusPct: 0.3,
      passiveUnlockText: "👻 ซุ่มเสรี Lv1!",
      passiveCritBonus: 0.0,
      passiveLifesteal: 0.02,
      passiveSpeedAdditive: 0.4,
      passiveLv2KillReq: 5,
      passiveLv2HpBonusPct: 0.2,
      passiveLv2UnlockText: "👻 ซุ่มเสรี AWAKENED!",
      passiveLv2CritBonus: 0.04,
      speedOnHit: 20,
      speedOnHitDuration: 0.4,
      damageMultiplierPerLevel: 0.09,
      cooldownReductionPerLevel: 0.04,
      maxHpPerLevel: 8,
      teleportCooldown: 18,
      teleportEnergyCost: 20,
      cloneCooldown: 25,
      cloneEnergyCost: 30,
      cloneDuration: 8,
      cloneProximityRange: 90,
      cloneProximityDmgMult: 0.6,
      dashStealthDuration: 1.5,
      phantomBlinkEnabled: true,
      phantomBlinkAmbushWindow: 2.0,
      phantomBlinkDmgMult: 1.4,
      stealthChainBonus: 0.18,
      weaponMasterReq: 5,
    },
    auto: {
      name: "Auto",
      radius: 20,
      hp: 230,
      maxHp: 230,
      energy: 100,
      maxEnergy: 100,
      energyRegen: 20,
      moveSpeed: 260,
      dashSpeed: 490,
      dashDistance: 170,
      dashCooldown: 1.7,
      heatWaveRange: 180,
      heatWaveCooldown: 0.22,
      wanchaiDuration: 8.0,
      wanchaiCooldown: 12,
      wanchaiEnergyCost: 25,
      wanchaiPunchRate: 0.1,
      wanchaiDamage: 18,
      standSpeedMod: 1.5,
      standDamageReduction: 0.4,
      standCritBonus: 0.1,
      standMoveSpeed: 340,
      standPunchRange: 110,
      standLeashRadius: 420,
      standKnockback: 240,
      playerMeleeCooldown: 0.12,
      playerMeleeRange: 200,
      playerMeleeRangeFar: 320,
      playerRushRange: 200,
      playerRushCooldown: 0.1,
      vacuumRange: 340,
      vacuumForce: 1900,
      vacuumCooldown: 6,
      vacuumEnergyCost: 20,
      vacuumStunDur: 0.5,
      vacuumPullDur: 0.45,
      vacuumDamage: 18,
      vacuumIgniteDuration: 1.5,
      vacuumIgniteDPS: 12,
      vacuumHeatGain: 25,
      standPullCooldown: 10,
      detonationRange: 240,
      detonationCooldown: 8,
      detonationEnergyCost: 30,
      detonationBaseDamage: 55,
      detonationHeatScaling: 1.2,
      detonationDamageHardCap: 600,
      chargeDamageMultMax: 2.5,
      heatMax: 100,
      heatPerHit: 12,
      heatPerPlayerHit: 8,
      heatPerDamageTaken: 0.5,
      heatDecayRate: 8,
      heatDecayRateActive: 0,
      heatTierWarm: 34,
      heatTierHot: 67,
      heatTierOverheat: 100,
      heatDmgWarm: 1.1,
      heatDmgHot: 1.2,
      heatDmgOverheat: 1.3,
      heatPunchRateWarm: 0.92,
      heatPunchRateHot: 0.85,
      heatCritBonusOverheat: 0.12,
      heatHpDrainOverheat: 5,
      heatOnKillWanchai: 15,
      heatHealOnKillWanchai: 0.05,
      baseCritChance: 0.06,
      critMultiplier: 2.2,
      stealthCooldown: 12,
      stealthCost: 9999,
      stealthDrain: 0,
      stealthSpeedBonus: 1.0,
      expToNextLevel: 100,
      expLevelMult: 1.3,
      damageMultiplierPerLevel: 0.08,
      cooldownReductionPerLevel: 0.04,
      maxHpPerLevel: 16,
      passiveUnlockLevel: 5,
      passiveUnlockStealthCount: 0,
      passiveHpBonusPct: 0.35,
      passiveUnlockText: "💥 วันชัยโอเวอร์ไดรฟ์!",
      passiveCritBonus: 0.06,
      passiveLifesteal: 0.025,
      passiveHeatGainBonus: 1.2,
      passiveHeatNoDecayOnMove: false,
      vacuumEarlyUnlock: true,
      rageModeHpThreshold: 0.3,
      rageDamageMult: 1.3,
      rageDamageReduction: 0.2,
      speedOnHit: 15,
      speedOnHitDuration: 0.35,
      coldDamageMult: 0.75,
      coldSpeedMult: 0.9,
      heatIdleDecayRate: 8,
      heatIdleDecayDelay: 2.0,
      ventExplosionRange: 160,
      ventExplosionDamage: 45,
      heatOnKillSupercharge: 30,
      oraComboSuperchargeMin: 5,
      standPullRange: 380,
      standPullDamage: 18,
      chargeMaxTime: 1.5,
      chargeRangeMultMax: 1.3,
      standGuardReduction: 0.6,
      vacuumEarlyHeatGain: 10,
      standMeterMax: 100,
      standMeterDrainRate: 8,
      standMeterPerHit: 1,
      standMeterOnKill: 8,
      standMeterDrainCold: 3.0,
      standMeterDrainOverheat: 2.0,
    },
    poom: {
      name: "Poom",
      radius: 20,
      hp: 165,
      maxHp: 165,
      energy: 100,
      maxEnergy: 100,
      energyRegen: 12,
      moveSpeed: 298,
      dashSpeed: 520,
      dashDistance: 170,
      dashCooldown: 1.65,
      expToNextLevel: 100,
      expLevelMult: 1.3,
      riceDamage: 62,
      riceCooldown: 0.42,
      riceSpeed: 600,
      riceRange: 750,
      riceColor: "#ffffff",
      critChance: 0.12,
      critMultiplier: 3,
      eatRiceCooldown: 10,
      eatRiceEnergyCost: 15,
      eatRiceDuration: 6,
      eatRiceSpeedMult: 1.3,
      eatRiceCritBonus: 0.12,
      nagaCooldown: 22,
      nagaDuration: 9,
      nagaEnergyCost: 25,
      nagaDamage: 100,
      nagaSpeed: 525,
      nagaSegments: 18,
      nagaSegmentDistance: 32,
      nagaRadius: 22,
      speedOnHit: 18,
      speedOnHitDuration: 0.35,
      damageMultiplierPerLevel: 0.09,
      cooldownReductionPerLevel: 0.05,
      maxHpPerLevel: 10,
      passiveUnlockLevel: 4,
      passiveUnlockStealthCount: 0,
      passiveHpBonusPct: 0.45,
      passiveUnlockText: "🌾 ราชาอีสาน!",
      passiveCritBonus: 0.06,
      passiveLifesteal: 0.025,
      cosmicDamageMult: 1.25,
      cosmicHpRegen: 6,
      cosmicStickyDurationBonus: 1.0,
      sticky: {
        maxStacks: 5,
        stackDuration: 1.5,
        slowPerStack: 0.04,
        maxSlowDuration: 1.5,
      },
      fragment: {
        count: 2,
        damagePct: 0.5,
        bounces: 1,
        bossReflectionMultiplier: 1.35,
      },
      garudaCooldown: 24,
      garudaEnergyCost: 30,
      garudaDuration: 9,
      garudaDamage: 120,
      garudaOrbitRadius: 120,
      garudaOrbitSpeed: 2.2,
      garudaDiveCooldown: 1.8,
      garudaDiveSpeed: 820,
      garudaReturnSpeed: 620,
      garudaEatRiceBonus: 1.5,
      nagaIgniteDuration: 0.8,
      cosmicNagaBurnDPS: 30,
      cosmicGarudaRadiusMult: 1.5,
      ritualBossDmgCapPct: 0.35,
      ritualBossDmgCapCosmicPct: 0.45,
    },
    pat: {
      name: "Pat",
      radius: 17,
      hp: 140,
      maxHp: 140,
      energy: 100,
      maxEnergy: 100,
      energyRegen: 18,
      moveSpeed: 285,
      dashSpeed: 530,
      dashDistance: 175,
      dashCooldown: 1.6,
      weapons: {
        katana: {
          name: "KATANA",
          damage: 42,
          cooldown: 0.32,
          range: 750,
          speed: 820,
          color: "#7ec8e3",
          icon: "🔵",
        },
      },
      meleeRange: 150,
      meleeDamageMulti: 2.0,
      meleeComboHits: 3,
      meleeComboWindow: 0.18,
      meleeCooldown: 0.55,
      baseCritChance: 0.08,
      critMultiplier: 2.4,
      bladeGuardSpeedMult: 0.6,
      bladeGuardMaxDuration: 3.0,
      bladeGuardCooldown: 5.0,
      bladeGuardReflectRadius: 55,
      qEnergyCost: 22,
      zanzoRange: 280,
      zanzoCooldown: 7.0,
      zanzoLandingRange: 120,
      zanzoCritBonus: 0.4,
      zanzoAmbushWindow: 1.5,
      zanzoGhostCount: 4,
      zanzoGhostFadeDur: 0.35,
      rEnergyCost: 40,
      iaidoRange: 400,
      iaidoCooldown: 14.0,
      iaidoChargeDuration: 0.6,
      iaidoDamage: 180,
      iaidoCritMulti: 3.5,
      iaidoFreezeDuration: 0.5,
      iaidoBloodParticles: 18,
      expToNextLevel: 100,
      expLevelMult: 1.3,
      damageMultiplierPerLevel: 0.09,
      cooldownReductionPerLevel: 0.04,
      maxHpPerLevel: 7,
      passiveUnlockLevel: 3,
      passiveUnlockStealthCount: 0,
      passiveHpBonusPct: 0.25,
      passiveUnlockText: "⚔️ โรนินตื่น!",
      passiveCritBonus: 0.05,
      passiveLifesteal: 0.02,
      passiveMeleeDmgBonus: 0.15,
      speedOnHit: 18,
      speedOnHitDuration: 0.38,
      reflectDamageMult: 2.0,
      perfectParryWindow: 0.15,
      perfectParryReflectMult: 4.0,
      perfectParryEnergyRestore: 20,
      perfectParryIFrameDur: 0.4,
      perfectParryScreenFreeze: 0.05,
      iaidoPointBlankRange: 45,
      iaidoPointBlankDmgMult: 2.0,
      iaidoPointBlankIFrameDur: 1.5,
      iaidoCinematicDur: 0.55,
      graphReflectRange: 80,
      graphReflectDamageMult: 2.0,
    },
  },
  drone: {
    radius: 12,
    damage: 15,
    range: 300,
    fireRate: 1.0,
    projectileSpeed: 700,
    projectileColor: "#00e5ff",
    speed: 250,
    orbitRadius: 75,
    orbitSpeed: 1.1,
    lerpBase: 0.02,
    bobAmplitude: 8,
    bobSpeed: 3.5,
    overdriveCombo: 15,
    overdriveFireRate: 1.5,
    overdriveColor: "#facc15",
    overdriveGlow: "#f59e0b",
    overdriveLinger: 4.0,
  },
  enemy: {
    radius: 18,
    colors: ["#ef4444", "#f59e0b", "#8b5cf6"],
    expValue: 18,
    chaseRange: 150,
    projectileSpeed: 500,
    baseHp: 40,
    hpPerWave: 0.19,
    baseSpeed: 85,
    speedPerWave: 6,
    baseDamage: 8,
    damagePerWave: 1.4,
    shootCooldown: [2.5, 4.5],
    shootRange: 550,
  },
  tank: {
    radius: 25,
    color: "#78716c",
    expValue: 45,
    powerupDropMult: 1.5,
    baseHp: 100,
    hpPerWave: 0.2,
    baseSpeed: 60,
    speedPerWave: 3,
    baseDamage: 18,
    damagePerWave: 2.5,
    meleeRange: 55,
  },
  mage: {
    radius: 16,
    color: "#a855f7",
    expValue: 55,
    powerupDropMult: 1.3,
    orbitDistance: 300,
    orbitDistanceBuffer: 100,
    baseHp: 28,
    hpPerWave: 0.22,
    baseSpeed: 70,
    speedPerWave: 5,
    baseDamage: 12,
    damagePerWave: 1.8,
    soundWaveCooldown: 10,
    soundWaveRange: 300,
    soundWaveConfuseDuration: 0.6,
    meteorCooldown: 13,
    meteorDamage: 24,
    meteorBurnDuration: 3,
    meteorBurnDPS: 4.0,
  },
  healer: {
    radius: 16,
    color: "#10b981",
    expValue: 40,
    powerupDropMult: 1.2,
    orbitDistance: 300,
    orbitDistanceBuffer: 90,
    baseHp: 32,
    hpPerWave: 0.2,
    baseSpeed: 80,
    speedPerWave: 4,
    baseDamage: 10,
    damagePerWave: 1.6,
    healInterval: 5.0,
    healRange: 260,
    healAmount: 12,
    healAmountPerWave: 0.6,
    shootCooldown: [2.2, 3.6],
    shootRange: 420,
    projectileSpeed: 520,
  },
  sniper: {
    radius: 17,
    color: "#38bdf8",
    expValue: 50,
    powerupDropMult: 1.25,
    preferredRange: 430,
    fleeRange: 250,
    baseHp: 30,
    hpPerWave: 0.18,
    baseSpeed: 85,
    speedPerWave: 4,
    baseDamage: 16,
    damagePerWave: 2.2,
    shootCooldown: [3.0, 4.0],
    shootRange: 520,
    laserChargeTime: 0.7,
    projectileSpeed: 900,
  },
  boss: {
    radius: 50,
    spawnY: -330,
    contactDamage: 30,
    speechInterval: 10,
    nextWaveDelay: 2000,
    log457HealRate: 0.06,
    chalkProjectileSpeed: 600,
    attackFireRate: 0.1,
    phase2AttackFireRate: 0.05,
    ultimateProjectileSpeed: 400,
    baseHp: 5200,
    hpMultiplier: 1.32,
    moveSpeed: 140,
    phase2Speed: 190,
    phase2Threshold: 0.5,
    phase2ThresholdByEnc: [null, 0.5, null, 0.6, null, 0.65],
    phase3ThresholdByEnc: [null, null, null, 0.3, null, 0.35],
    chalkDamage: 13,
    ultimateDamage: 35,
    ultimateBullets: 20,
    phase2UltimateBullets: 28,
    slamDamage: 60,
    slamRadius: 360,
    slamCooldown: 14,
    graphDamage: 70,
    graphLength: 1600,
    graphDuration: 20,
    graphCooldown: 16,
    matrixGridCooldown: 22.0,
    log457ChargeDuration: 2,
    log457ActiveDuration: 6,
    log457StunDuration: 1.2,
    log457Cooldown: 30,
    log457AttackBonus: 0.09,
    log457AttackGrowth: 0.04,
    burstArmorThresholdPct: 0.3,
    burstArmorReduction: 0.4,
    burstArmorDuration: 4.0,
    burstArmorCooldown: 25,
    phase2: {
      barkDamage: 32,
      barkRange: 600,
      barkCooldown: 3.2,
      enrageSpeedMult: 2.0,
      dogColor: "#d97706",
      chalkWallCooldown: 12.0,
      chalkWallDamage: 15,
      chalkWallLength: 340,
      chalkWallDuration: 6.0,
      dogPackCooldown: 18.0,
    },
    bossDog: {
      hp: 2000,
      speed: 280,
      damage: 30,
      radius: 24,
      color: "#d97706",
    },
    phase3Threshold: 0.25,
    phase3: {
      auraColor: "#38bdf8",
      goldfishCooldown: 5.5,
      goldfishCount: 4,
      bubbleCooldown: 6.0,
      bubbleCount: 5,
      slowFactor: 0.5,
      slowDuration: 2.0,
    },
    goldfishMinion: {
      hp: 100,
      speed: 165,
      damage: 18,
      radius: 12,
      wobbleAmp: 40,
      wobbleFreq: 3.5,
      color: "#fb923c",
    },
    bubbleProjectile: {
      speed: 100,
      damage: 30,
      radius: 18,
      color: "rgba(186, 230, 253, 0.6)",
    },
    first: {
      hpBaseMult: 0.72,
      advancedHpMult: 0.85,
      speedBaseMult: 1.55,
      advancedSpeedMult: 1.35,
      contactDamageMult: 1.2,
      cooldowns: {
        suvat: 8.0,
        orbit: 12.0,
        freeFall: 15.0,
        rocket: 9.0,
        sandwich: 18.0,
      },
      suvat: { windUp: 0.9, accel: 1900, maxDur: 1.2, damage: 80 },
      orbit: {
        radius: 115,
        speed: 2.8,
        duration: 3.5,
        projDamage: 24,
        projSpeed: 520,
      },
      freeFall: { warnDur: 1.8, aoeRadius: 140, damage: 95, advMult: 1.25 },
      rocket: { baseDmg: 28, advMult: 1.3, baseSpeed: 480 },
      berserk: { projDamage: 22, advMult: 1.3, projSpeed: 540, fireCd: 2.2 },
      dodge: { radius: 130, impulse: 420, cd: 1.2 },
    },
    domainExpansion: {
      dangerPct: 0.62,
      dangerPctMax: 0.84,
      subPhaseA_warnDur: 2.0,
      subPhaseB_dangerPctStep: 0.06,
      subPhaseB_chalkInterval: 0.8,
      subPhaseB_chalkCount: 3,
      subPhaseB_chalkSpeed: 460,
      subPhaseB_chalkDamage: 18,
      subPhaseB_safeCellShift: true,
      subPhaseC_teacherFuryChance: 0.3,
    },
    gravitationalSingularity: {
      castDur: 2.5,
      endDur: 2.0,
      cooldown: 999,
      pullDur: 4.0,
      escapeDur: 4.5,
      tidalDur: 4.5,
      collapseDur: 2.5,
      pullForce: 95,
      pushForce: 130,
      tidalForce: 110,
      tidalPeriod: 3.0,
      collapseForce: 220,
      projPullForce: 60,
      orbitalCount: 6,
      orbitalRadius: 90,
      orbitalSpeed: 2.2,
      orbitalDamage: 25,
      pulse2FireCd: 1.2,
      pulse2Teleports: 4,
      pulse3ZoneCount: 3,
      collapseRadius: 380,
      collapseDamage: 40,
      safeRadius: 75,
      contactRadius: 70,
      contactDPS: 18,
      contactTickCd: 0.7,
      repulseForce: 260,
      collapseInnerRadius: 110,
      collapseInnerDamage: 65,
    },
  },
  powerups: {
    radius: 20,
    dropRate: 0.18,
    lifetime: 14,
    healAmount: 20,
    damageBoost: 1.4,
    damageBoostDuration: 8,
    speedBoost: 1.3,
    speedBoostDuration: 8,
  },
  waves: {
    spawnDistance: 800,
    bossSpawnDelay: 3000,
    maxWaves: 15,
    minKillsForNoDamage: 5,
    enemiesBase: 5,
    enemiesPerWave: 2.0,
    tankSpawnChance: 0.1,
    mageSpawnChance: 0.12,
    healerSpawnChance: 0.06,
    sniperSpawnChance: 0.05,
    bossEveryNWaves: 3,
    glitchGracePeriod: 4000,
    fogWaves: [2, 8, 11, 14],
    speedWaves: [4, 7, 13],
    glitchWaves: [5, 10],
    darkWave: 1,
  },
  score: {
    basicEnemy: 100,
    tank: 200,
    mage: 280,
    boss: 6000,
    powerup: 120,
    achievement: 500,
  },
  database: {
    x: 500,
    y: -490,
    interactionRadius: 90,
    url: "https://claude.ai/public/artifacts/649de47e-b97f-41ad-ae66-c944d35eb24f",
    auraColor: "#06b6d4",
    auraLineWidth: 2,
    auraDash: [6, 4],
    auraAlphaMult: 0.25,
    glowColor: "#06b6d4",
    glowSpeedMs: 600,
    glowBlurMax: 14,
    labelColor: "#67e8f9",
    labelFont: "bold 7px Arial",
    labelText: "MTC DATABASE",
  },
  shop: {
    x: -500,
    y: 490,
    interactionRadius: 90,
    slotCount: 3,
    rerollCost: 200,
    auraColor: "#facc15",
    auraLineWidth: 2,
    auraDash: [6, 4],
    auraAlphaMult: 0.3,
    glowColor: "#facc15",
    glowSpeedMs: 700,
    glowBlurMax: 18,
    bounceSpeedMs: 500,
    bounceAmplitude: 3,
    coinBounceSpeedMs: 350,
    coinBounceAmplitude: 4,
    labelColor: "#fbbf24",
    labelFont: "bold 7px Arial",
    labelText: "MTC CO-OP STORE",
  },
  mtcRoom: {
    healRate: 30,
    maxStayTime: 4,
    cooldownTime: 10,
    size: 300,
    dashResetOnEntry: true,
    crisisHpPct: 0.25,
    crisisHealBonus: 35,
    buffCycleDuration: [8, 6, 0],
    buffCycleMagnitude: [0.15, 0.1, 0.35],
    buffCycleNames: ["DMG +15%", "SPD +10%", "CDR BURST"],
    buffCycleColors: ["#f97316", "#22d3ee", "#a78bfa"],
    buffCycleIcons: ["⚔", "💨", "⚡"],
  },
  interactive: {
    hackTerminal: {
      interactionRadius: 80,
      channelDuration: 3.0,
      pauseDuration: 15.0, // Pauses wave timer & spawns
      cooldown: 45.0,
      color: "#10b981", // Emerald-500
      icon: "💻",
    },
    medStation: {
      interactionRadius: 60,
      healAmount: 50,
      cooldown: 30.0,
      usesPerWave: 2,
      color: "#ef4444", // Red-500
      icon: "🏥",
    },
    ammoCrate: {
      interactionRadius: 60,
      energyAmount: 100, // Full refill
      cooldown: 30.0,
      usesPerWave: 2,
      color: "#f59e0b", // Amber-500
      icon: "🔋",
    },
    powerNode: {
      radius: 250, // Buff radius
      damageBonus: 0.2, // +20% damage
      activeColor: "#8b5cf6", // Violet-500
      inactiveColor: "#4b5563", // Gray-600
    },
  },
  LIGHTING: {
    ambientLight: 0.72,
    cycleDuration: 60,
    nightMinLight: 0.12,
    dayMaxLight: 0.95,
    playerLightRadius: 185,
    projectileLightRadius: 55,
    mtcServerLightRadius: 140,
    shopLightRadius: 100,
    dataPillarLightRadius: 85,
    serverRackLightRadius: 65,
    nightR: 3,
    nightG: 6,
    nightB: 20,
  },
  ai: {
    decisionInterval: 0.5,
    personalities: {
      basic: { aggression: 0.6, caution: 0.2, teamwork: 0.3 },
      tank: { aggression: 0.8, caution: 0.1, teamwork: 0.5 },
      mage: { aggression: 0.3, caution: 0.8, teamwork: 0.2 },
    },
    actions: {
      attack: { base: 1.0 },
      retreat: { base: 0.8, hpThreshold: 0.3 },
      flank: { base: 0.6, optimalDist: 220 },
    },
    squad: {
      coordinationRadius: 300,
      squadInterval: 1.0,
    },
  },
  map: {
    size: 3000,
    objectDensity: 0.12,
    objectTypes: [
      "desk",
      "tree",
      "server",
      "datapillar",
      "bookshelf",
      "blackboard",
      "database",
      "coopstore",
      "hackTerminal",
      "medStation",
      "ammoCrate",
      "powerNode",
    ],
    objectSizes: {
      desk: { w: 60, h: 40 },
      tree: { w: 50, h: 50 },
      server: { w: 45, h: 80 },
      datapillar: { w: 35, h: 70 },
      bookshelf: { w: 80, h: 40 },
      vendingmachine: { w: 40, h: 70 },
    },
    wallPositions: [
      { x: -1500, y: -50, w: 50, h: 100 },
      { x: 1450, y: -50, w: 50, h: 100 },
      { x: -50, y: -1500, w: 100, h: 50 },
      { x: -50, y: 1450, w: 100, h: 50 },
      { x: 400, y: -420, w: 18, h: 200 },
      { x: 400, y: -100, w: 18, h: 200 },
      { x: 400, y: 160, w: 18, h: 120 },
      { x: -418, y: -420, w: 18, h: 200 },
      { x: -418, y: -100, w: 18, h: 200 },
      { x: -418, y: 160, w: 18, h: 120 },
      { x: -180, y: 340, w: 130, h: 18 },
      { x: 50, y: 340, w: 130, h: 18 },
      { x: -560, y: 420, w: 18, h: 100 },
      { x: 542, y: 420, w: 18, h: 100 },
      { x: -180, y: -370, w: 130, h: 18 },
      { x: 50, y: -370, w: 130, h: 18 },
      { x: -180, y: -480, w: 18, h: 110 },
      { x: 162, y: -480, w: 18, h: 110 },
      { x: -1100, y: -620, w: 30, h: 30 },
      { x: -380, y: -620, w: 30, h: 30 },
    ],
    mapColors: {
      floor: "#080d18",
      floorAlt: "#060a14",
      treeLight: "#4a7a1a",
      treeMid: "#243d0e",
      treeDark: "#142208",
      treeTrunk: "#5c2204",
      deskTop: "#251c0a",
      deskLegs: "#140e04",
      serverBody: "#0d1117",
      serverLightOn: "#fbbf24",
      serverLightOff: "#3d1502",
      pillarBase: "#1e293b",
      pillarCircuit: "#f59e0b",
      bookColors: [
        "#c26010",
        "#a85020",
        "#e8901a",
        "#8c4010",
        "#b87010",
        "#9a5a10",
        "#fbbf24",
      ],
      wallColor: "#1f1610",
      wallBrick: "#352510",
      whiteboardGreen: "#0f2b0c",
      chalkWhite: "#fef9ee",
      dbBody: "#080f1a",
      dbAccent: "#fbbf24",
      dbRackOn: "#f59e0b",
      dbRackOff: "#3d2a00",
      shopBody: "#0f0a04",
      shopAccent: "#f97316",
      shopSign: "#fcd34d",
      shopCounter: "#1c1008",
      shopShelf: "#78350f",
    },
  },
};

const SHOP_ITEMS = [
  {
    id: "potion",
    name: "Energy Drink",
    icon: "🧃",
    cost: 300,
    type: "instant",
    heal: 60,
    desc: "ฟื้นฟูเลือด 60 หน่วย",
    color: "#22c55e",
  },
  {
    id: "shield",
    name: "Energy Shield",
    icon: "🛡️",
    cost: 600,
    type: "instant",
    desc: "บล็อกการโจมตีครั้งต่อไปหนึ่งครั้ง",
    color: "#8b5cf6",
  },
  {
    id: "maxHp",
    name: "Vital Supplement",
    icon: "❤️",
    cost: 500,
    type: "permanent",
    hpBonus: 15,
    desc: "เพิ่มเลือดสูงสุด 15 หน่วย",
    color: "#f87171",
  },
  {
    id: "dmgUp",
    name: "Weapon Tuner",
    icon: "🔧",
    cost: 800,
    type: "permanent",
    dmgPct: 0.05,
    desc: "เพิ่มดาเมจ 5%",
    color: "#f59e0b",
  },
  {
    id: "speedUp",
    name: "Lightweight Boots",
    icon: "👟",
    cost: 500,
    type: "permanent",
    speedPct: 0.05,
    desc: "เพิ่มความเร็ว 5%",
    color: "#06b6d4",
  },
  {
    id: "cdr",
    name: "Focus Crystal",
    icon: "🔮",
    cost: 700,
    type: "permanent",
    cdrPct: 0.05,
    desc: "ลดคูลดาวน์สกิล 5%",
    color: "#a78bfa",
  },
  {
    id: "reflectArmor",
    name: "Reflect Armor",
    icon: "🪞",
    cost: 900,
    type: "permanent",
    reflectPct: 0.15,
    desc: "สะท้อน 15% ดาเมจกลับหาศัตรู",
    color: "#818cf8",
  },
  {
    id: "shieldBubble",
    name: "Shield Bubble",
    icon: "🫧",
    cost: 500,
    type: "instant",
    bubbleHits: 3,
    desc: "บล็อกการโจมตี 3 ครั้ง",
    color: "#7dd3fc",
  },
  {
    id: "speedWave",
    name: "Adrenaline Wave",
    icon: "⚡",
    cost: 400,
    type: "instant",
    speedMult: 1.3,
    duration: 8,
    desc: "เพิ่มความเร็ว +30% เป็นเวลา 8 วินาที",
    color: "#fbbf24",
  },
  {
    id: "cdrRound",
    name: "Cooldown Round",
    icon: "🔄",
    cost: 600,
    type: "instant",
    desc: "รีเซ็ตคูลดาวน์สกิลทั้งหมดทันที",
    color: "#34d399",
  },
  {
    id: "kaoAmmo",
    name: "Ghost Rounds",
    icon: "👻",
    cost: 750,
    type: "permanent",
    charReq: "kao",
    desc: "[KAO] Teleport charges +1 (สูงสุด 4)",
    color: "#facc15",
  },
  {
    id: "poomRice",
    name: "Sacred Rice Bag",
    icon: "🍚",
    cost: 650,
    type: "permanent",
    charReq: "poom",
    desc: "[POOM] ลด CD ของ Naga/Garuda/Ritual 15%",
    color: "#4ade80",
  },
  {
    id: "autoCore",
    name: "Heat Core",
    icon: "🔥",
    cost: 850,
    type: "permanent",
    charReq: "auto",
    desc: "[AUTO] ถึง HOT tier ง่ายขึ้น 15%",
    color: "#fb923c",
  },
];

const ACHIEVEMENT_DEFS = [
  {
    id: "first_blood",
    name: "First Blood",
    desc: "เคลียร์ศัตรูตัวแรก",
    icon: "⚔️",
    reward: { type: "hp", value: 5, text: "+5 Max HP" },
  },
  {
    id: "wave_1",
    name: "Wave Survivor",
    desc: "ผ่าน Wave แรก",
    icon: "🌊",
    reward: { type: "hp", value: 5, text: "+5 Max HP" },
  },
  {
    id: "wave_5",
    name: "MTC Veteran",
    desc: "รอดชีวิตถึง Wave 5",
    icon: "🎖️",
    reward: { type: "hp", value: 10, text: "+10 Max HP" },
  },
  {
    id: "wave_10",
    name: "MTC Legend",
    desc: "รอดชีวิตถึง Wave 10",
    icon: "🏆",
    reward: { type: "hp", value: 15, text: "+15 Max HP" },
  },
  {
    id: "manop_down",
    name: "1st Manop Slayer",
    desc: "เอาชนะครูมานพครั้งแรก",
    icon: "👑",
    reward: { type: "damage", value: 0.02, text: "+2% Damage" },
  },
  {
    id: "first_down",
    name: "Physics Breaker",
    desc: "เอาชนะครูเฟิร์สแซนด์วิชหมู",
    icon: "⚛️",
    reward: { type: "damage", value: 0.02, text: "+2% Damage" },
  },
  {
    id: "parry_master",
    name: "Return to Sender",
    desc: "Parry แซนด์วิชหมูกลับไปหาครูเฟิร์ส",
    icon: "🥪",
    reward: { type: "damage", value: 0.03, text: "+3% Damage" },
  },
  {
    id: "no_damage",
    name: "Untouchable",
    desc: "ผ่าน Wave โดยไม่โดนดาเมจ",
    icon: "🛡️",
    reward: { type: "hp", value: 10, text: "+10 Max HP" },
  },
  {
    id: "crit_master",
    name: "Critical Master",
    desc: "ตีติดคริติคอล 5 ครั้ง",
    icon: "💥",
    reward: { type: "crit", value: 0.01, text: "+1% Crit Chance" },
  },
  {
    id: "bullet_time_kill",
    name: "Time Bender",
    desc: "ฆ่าศัตรูขณะ Bullet Time 3 ตัว",
    icon: "🕐",
    reward: { type: "cdr", value: 0.01, text: "-1% Cooldown" },
  },
  {
    id: "barrel_bomber",
    name: "Expert Bomber",
    desc: "ฆ่าศัตรูด้วยถังระเบิด 3 ตัว",
    icon: "🛢️",
    reward: { type: "damage", value: 0.02, text: "+2% Damage" },
  },
  {
    id: "speedster",
    name: "Speedster",
    desc: "ใช้ Dash 20 ครั้ง",
    icon: "⚡",
    reward: { type: "speed", value: 0.02, text: "+2% Speed" },
  },
  {
    id: "collector",
    name: "MTC Collector",
    desc: "เก็บ Power-up 10 ชิ้น",
    icon: "💎",
    reward: { type: "speed", value: 0.02, text: "+2% Speed" },
  },
  {
    id: "shopaholic",
    name: "MTC Shopaholic",
    desc: "ซื้อไอเทมจากร้านค้า 5 ครั้ง",
    icon: "🛒",
    reward: { type: "speed", value: 0.02, text: "+2% Speed" },
  },
  {
    id: "shop_max",
    name: "Capitalism",
    desc: "ซื้อบัฟร้านค้าจนเต็มสแต็ก 1.5x",
    icon: "📈",
    reward: { type: "speed", value: 0.02, text: "+2% Speed" },
  },
  {
    id: "ghost",
    name: "The Ghost of MTC",
    desc: "ซุ่มสำเร็จ 10 ครั้ง",
    icon: "👻",
    reward: { type: "cdr", value: 0.01, text: "-1% Cooldown" },
  },
  {
    id: "weapon_master",
    name: "Arsenal",
    desc: "ใช้อาวุธครบทั้ง 3 แบบในเกมเดียว",
    icon: "🔫",
    reward: { type: "damage", value: 0.02, text: "+2% Damage" },
  },
  {
    id: "kao_awakened",
    name: "Weapon Master Awakened",
    desc: "ปลดล็อคสกิล Weapon Master ของเก้าสำเร็จ",
    icon: "⚡",
    reward: { type: "crit", value: 0.01, text: "+1% Crit Chance" },
  },
  {
    id: "drone_master",
    name: "Drone Master",
    desc: "ปลดล็อค Drone Overdrive ครั้งแรก",
    icon: "🤖",
    reward: { type: "damage", value: 0.02, text: "+2% Damage" },
  },
  {
    id: "naga_summoner",
    name: "Naga Summoner",
    desc: "อัญเชิญพญานาค 3 ครั้ง",
    icon: "🐍",
    reward: { type: "cdr", value: 0.01, text: "-1% Cooldown" },
  },
  {
    id: "stand_rush_kill",
    name: "WANCHAI-REQUIEM",
    desc: "ฆ่าศัตรูด้วย Stand Rush 10 ตัว",
    icon: "🥊",
    reward: { type: "damage", value: 0.02, text: "+2% Damage" },
  },
  {
    id: "ritual_wipe",
    name: "Sticky Situation",
    desc: "ฆ่าศัตรู 3 ตัวขึ้นไปด้วย Ritual Burst ครั้งเดียว",
    icon: "🌾",
    reward: { type: "damage", value: 0.02, text: "+2% Damage" },
  },
  {
    id: "scorched_soul",
    name: "SCORCHED SOUL",
    desc: "ปลดล็อค Passive ออโต้ด้วยการ Overheat ครั้งแรก",
    icon: "🔥",
    reward: { type: "damage", value: 0.02, text: "+2% Damage" },
  },
  {
    id: "ritual_king",
    name: "King of Isan",
    desc: "ปลดล็อค Passive ภูมิด้วย Ritual Burst ครั้งแรก",
    icon: "🌾",
    reward: { type: "hp", value: 10, text: "+10 Max HP" },
  },
];

const WAVE_SCHEDULE = Object.freeze({
  fogWaves: [2, 8, 11, 14],
  speedWaves: [4, 7, 13],
  glitchWaves: [5, 10],
  darkWave: 1,
  bossWaves: [3, 6, 9, 12, 15],
  weatherChance: 0.35,
  snowChance: 0.12,
  maxWaves: 15,
  healerFirstWave: 4,
  sniperFirstWave: 7,
});

window.BALANCE = BALANCE;
window.SHOP_ITEMS = SHOP_ITEMS;
window.ACHIEVEMENT_DEFS = ACHIEVEMENT_DEFS;
window.WAVE_SCHEDULE = WAVE_SCHEDULE;
